# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18P0xTS31q1P7nR4efg0Yy3QrClOxqMAe

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"resources/data01.rdf", format="xml")
g2.parse(github_storage+"resources/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""
from rdflib.plugins.sparql import prepareQuery
from rdflib.namespace import RDF, RDFS

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print("ORIGINAL GRAPH 1")
for s, p, o in g2:
    print(s,p,o)

query1 = prepareQuery('''
    SELECT DISTINCT ?Subject ?GivenName ?FamilyName ?Email WHERE {
        ?Subject rdf:type ns:Person.
        OPTIONAL{?Subject vcard:Given ?GivenName}.
        OPTIONAL{?Subject vcard:Family ?FamilyName}.
        OPTIONAL{?Subject vcard:EMAIL ?Email}
    }
    ''',
    initNs={"ns":Namespace("http://data.org#"),"vcard":VCARD, "rdf":RDF, "rdfs": RDFS}
    ) 

for r1 in g1.query(query1):
    for r2 in g2.query(query1, initBindings={"?Subject":r1.Subject}):
        if(r1.GivenName == None and r2.GivenName != None): g1.add((r1.Subject, VCARD.Given, r2.GivenName))
        if(r1.FamilyName == None and r2.FamilyName != None): g1.add((r1.Subject, VCARD.Family, r2.FamilyName))
        if(r1.Email == None and r2.Email != None): g1.add((r1.Subject, VCARD.EMAIL, r2.Email))

print("MODIFIED GRAPH 1")
for s, p, o in g1:
    print(s,p,o)