# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10I-oiwIamKm2U6elsUXyXGwItDWzKcpp

**Task 07: Querying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")
print(g.serialize(format="ttl"))

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

from rdflib.plugins.sparql import prepareQuery
NS = Namespace("http://somewhere#")
# RDFLib
for s, p, o in g.triples((None, RDFS.subClassOf, NS.Person)):
  print(s)
  for s2, p2, o1 in g.triples((None, RDFS.subClassOf, s)):
    print(s2)

# SPARQL

q1 = prepareQuery('''
  SELECT ?Subject WHERE { 
    ?Subject (rdfs:subClassOf/rdfs:subClassOf*) ns:Person. 
  }
  ''',
  initNs = {"rdfs": RDFS, "ns": NS}
)

for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# RDFLib
for s, p, o in g.triples((None, RDFS.subClassOf, NS.Person)):
  for s2, p2, o2 in g.triples((None, RDF.type, s)):
    print(s2)

for s3, p3, o3 in g.triples((None, RDF.type, NS.Person)):
  print(s3)


# SPARQL

q1 = prepareQuery('''
  SELECT ?Subject WHERE { 
    {?Subject a ns:Person} UNION
    {
      ?Classes (rdfs:subClassOf/rdfs:subClassOf*) ns:Person.
      ?Subject a ?Classes
      }
  }
  ''',
  initNs = {"rdfs": RDFS, "ns": NS, "rdf": RDF}
)

for r in g.query(q1):
  print(r)

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

# RDFLib

for s, p, o in g.triples((None, RDFS.subClassOf, NS.Person)):
  for s2, p2, o2 in g.triples((None, RDF.type, s)):
    print(s2)
    for s3, p3, o3 in g.triples((s2, None, None)):
      print(p3)

for s4, p4, o4 in g.triples((None, RDF.type, NS.Person)):
  print(s4)
  for s5, p5, o5 in g.triples((s4, None, None)):
      print(p5)

# SPARQL

q1 = prepareQuery('''
  SELECT ?Subject ?P WHERE { 
    {
      ?Subject a ns:Person.
      ?Subject ?P ?Value.
    } UNION
    {
      ?Classes (rdfs:subClassOf/rdfs:subClassOf*) ns:Person.
      ?Subject a ?Classes.
      ?Subject ?P ?Value.
      }
  }
  ''',
  initNs = {"rdfs": RDFS, "ns": NS, "rdf": RDF}
)

for r in g.query(q1):
  print(r)
