# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fg8vq0aav_xolC0i9o0dxkemzejW1DQI

**Task 07: Querying RDF(s)**
"""


github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

# TO DO
from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://somewhere#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
rdfs = Namespace("http://www.w3.org/2000/01/rdf-schema#")

# Visualize the results
# Using rdflib
for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)) :
  print(s)
print("--------")
# Using SPARQL
query = prepareQuery('''
  SELECT ?Subject WHERE { 
    ?Subject RDFS:subClassOf ns:Person
  } 
  ''',
  initNs= {"RDFS": rdfs, "ns":ns})
for result in g.query(query):
  print(result.Subject)

print("--------")
#for r in g.query(q1):
#  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
# Using rdfslib
for s,p,o in g.triples((None, RDF.type, ns.Person)) :
  print(s)
# We extract all of the subclasses of Person, and iterate the result
for s,p,o in g.triples((None, RDFS.subClassOf, ns.Person)):
  for s2,p2,o2 in g.triples((None, RDF.type, s)):
   print(s2)
print("--------")
# Using SPARQL
#query1= prepareQuery('''
#  SELECT ?Subject WHERE { 
#    ?Subject <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ns:Person
#  } 
#  ''',
#  initNs = {"ns":ns})
query2 = prepareQuery('''
  SELECT DISTINCT ?s WHERE { 
    ?Subject RDFS:subClassOf* ns:Person .
    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?Subject
  } 
  ''',
  initNs = {"ns":ns, "RDFS":RDFS})

#for result in g.query(query1) :
 # print(result.Subject)
for result in g.query(query2) :
  print(result.s)
# Visualize the results
print("--------")

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

# TO DO
# Using rdfslib
for s,p,o in g.triples((None, RDF.type, ns.Person)):
  for s2,p2,o2 in g.triples((s,None,None)):
    print(s2,p2,o2)
# For all of the Person subclasses
for s0,p0,o0 in g.triples((None, RDFS.subClassOf, ns.Person)):
 for s,p,o in g.triples((None, RDF.type, s0)):
   for s2,p2,o2 in g.triples((s,None,None)):
     print(s2,p2,o2)
print("--------")
# Using SPARQL
#query1 = prepareQuery('''
#  SELECT ?s ?p ?o WHERE { 
#    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ns:Person.
#    ?s ?p ?o.
#  } 
#  ''',
#  initNs = {"ns":ns})

query2 = prepareQuery('''
  SELECT DISTINCT ?s ?p ?o WHERE { 
    ?subclass RDFS:subClassOf* ns:Person .
    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?subclass.
    ?s ?p ?o.
  } 
  ''',
  initNs = {"ns":ns, "RDFS":RDFS})
#for result in g.query(query1):
#  print(result.s, result.p, result.o)

for result in g.query(query2):
  print(result.s, result.p, result.o)
# Visualize the results