# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aA_7cDJnS46kKnLS5uuCGN5_s3QANqk-

**Task 09: Data linking**
"""

#pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"resources/data03.rdf", format="xml")
g2.parse(github_storage+"resources/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""
from rdflib.namespace import RDF, RDFS
from rdflib.plugins.sparql import prepareQuery

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns1= Namespace("http://data.three.org#")
ns2= Namespace("http://data.four.org#")
OWL=Namespace("https://www.w3.org/TR/owl-ref/#")

q1 = prepareQuery('''
  SELECT ?Subject ?Given ?Family WHERE { 
    ?Subject vcard:Given ?Given. 
    ?Subject vcard:Family ?Family
  }
  ''',
  initNs = { "vcard": VCARD}
)

l=[]
s=[]

for r1 in g1.query(q1):
  s.append(r1.Subject)
  l.append([r1.Given,r1.Family])
for r in g2.query(q1):
  if([r.Given,r.Family] in l):
    print(s[l.index([r.Given,r.Family])], " / ",r.Subject,":  Able to link\n")
    g3.add((r.Subject,OWL.sameAs,s[l.index([r.Given,r.Family])]))
  else:
    print(r.Subject,":  Not able to link\n")
print("---------- LINKED ----------\n")
for (s,p,o) in g3:
  print(s,p,o)