# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aA_7cDJnS46kKnLS5uuCGN5_s3QANqk-

**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"resources/data03.rdf", format="xml")
g2.parse(github_storage+"resources/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.namespace import RDF, RDFS
from rdflib.plugins.sparql import prepareQuery
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")

q = prepareQuery('''
        SELECT DISTINCT ?Person ?Given ?Family WHERE{
            ?Person vcard:Given ?Given.
            ?Person vcard:Family ?Family
        }
    ''',
    initNs={"vcard":VCARD}
    )

rs = []

for r in g1.query(q):
  rs.append((r.Person, r.Given, r.Family))

for r2 in g2.query(q):
  for r1 in rs:
    if(r1[1] == r2.Given and r1[2] == r2.Family):
      g3.add((r1[0], OWL.sameAs, r2.Person))

for s,p,o in g3:
  print(s,p,o)