# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXraYt8-lBeu8vDsuuyt8JAHzBOfFKrW

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
# Visualize the results
ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type, RDFS.Class))
print("\n 6.1 resultado")
for s, p, o in g.triples((None,None,RDFS.Class)):
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
# Visualize the results
ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
print("\n 6.2 resultado")
for s, p, o in g.triples((None,RDFS.subClassOf,ns.Person)):
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# TO DO
# Visualize the results
ns = Namespace("http://somewhere#")
g.add((ns.JaneSmith, RDF.type, ns.Researcher))
print("\n 6.3 resultado")
for s, p, o in g.triples((None,RDF.type,ns.Researcher)):
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

# TO DO
# Visualize the results
ns = Namespace("http://somewhere#")
vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
g.add((ns.JaneSmith, vcard.FN, Literal("Jane Smith")))
g.add((ns.JaneSmith, vcard.Family, Literal("Smith")))
g.add((ns.JaneSmith, vcard.Given, Literal("Jane")))
print("\n 6.4 resultado")
for s, p, o in g.triples((ns.JaneSmith,None,None)):
  print(s,p,o)



"""**TASK 6.5: Add UPM as the university where John Smith works**"""



from rdflib import XSD
# TO DO
# Visualize the results
vcard=Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
ns = Namespace("http://somewhere#")
g.add((ns.UPM,RDF.type,ns.University))
g.add((ns.Works, RDF.type, RDF.Property))
g.add((ns.Works, RDFS.range, ns.University))
g.add((ns.JohnSmith,ns.Works,ns.UPM))
print("\n 6.5 resultado")
for s, p, o in g.triples((ns.UPM,RDF.type,None)):
  print(s,p,o)
for s, p, o in g.triples((ns.Works,None,None)):
  print(s,p,o)
for s, p, o in g.triples((ns.JohnSmith,ns.Works,None)):
  print(s,p,o)